project:
  type: website

website:
  title: "E155 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: lab1.qmd
        text: "Lab 1"
      - href: lab2.qmd
        text: "Lab 2"
      - href: lab3.qmd
        text: "Lab 3"
      - href: lab4.qmd
        text: "Lab 4"
      - href: lab5.qmd
        text: "Lab 5"
      - href: lab6.qmd
        text: "Lab 6"
      - href: lab7.qmd
        text: "Lab 7"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



